# Generated by Django 3.1 on 2022-01-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral',
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
